name: traccar_client
description: "Traccar Client"
publish_to: 'none'
version: 10.1.4+160

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  traccar_client_sdk: ^1.1.0
  shared_preferences: ^2.5.5
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  firebase_analytics: ^12.6.0
  firebase_crashlytics: ^5.4.0
  quick_actions: ^1.1.1
  rate_my_app: ^2.4.2
  shared_preferences_android: ^2.4.28
  mobile_scanner: ^7.4.2
  flutter_secure_storage: ^11.2.0
  app_links: ^7.0.0
  app_settings: ^9.0.0
  share_plus: ^13.3.1
  managed_configurations: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
